<?php
// uncomment the following to define a path alias
// Yii::setPathOfAlias('local','path/to/local-folder');

// This is the main Web application configuration. Any writable
// CWebApplication properties can be configured here.
return array(
	'basePath'=>dirname(__FILE__).DIRECTORY_SEPARATOR.'..',
	'name'=>'BeePond',
	'timeZone'=>'Australia/Sydney',

	// preloading 'log' component
	'preload'=>array('log'),

	// autoloading model and component classes
	'import'=>array(
		'application.models.*',
		'application.components.*',
		'application.extensions.*',
		'application.extensions.MongoYii.*',
		'application.extensions.MongoYii.validators.*',
		'application.extensions.MongoYii.behaviors.*',
		'application.extensions.MongoYii.util.*',
		'application.extensions.tmhoauth.*',
	),

	'modules'=>array(
		// uncomment the following to enable the Gii tool
		'gii'=>array(
			'class'=>'system.gii.GiiModule',
			'password'=>'pswd',
			// If removed, Gii defaults to localhost only. Edit carefully to taste.
			'ipFilters'=>array('125.168.201.231','125.168.201.231','123.243.75.188','::1'),
		),
	),

	// application components
	'components'=>array(
		'user'=>array(
			// enable cookie-based authentication
			'class' => 'WebUser',
			'allowAutoLogin'=>true,
		),
		// uncomment the following to enable URLs in path-format
		'urlManager'=>array(
			'urlFormat'=>'path',
			'showScriptName'=>false,
			'rules'=>array(
				'index'			=> '/site/index',
				'admin'			=> '/admin/index',
				'index' 			=> '/site/index',
				'ajax' 				=> '/site/ajax',
				'dashboard' 		=> '/site/dashboard',
				'profile' 			=> '/site/profile',
				'campaign' 			=> '/site/campaign',
				'campaignedit' 		=> '/site/campaignedit',
				'templateedit' 		=> '/site/templateedit',
				'feeds' 			=> '/site/feeds',
				'orderconfirmation' => '/site/orderconfirmation',
				'campaignfront' 	=> '/site/campaignfront',
				'front' 			=> '/site/front',
				'feeddetails' 		=> '/site/feeddetails',
				'testig' 			=> '/site/testig',
				'testfeedtr' 		=> '/site/testfeedtr',
				'testfeedig' 		=> '/site/testfeedig',
				'testfeedpt' 		=> '/site/testfeedpt',
				'testfeedyt' 		=> '/site/testfeedyt',
				'testfeedtw' 		=> '/site/testfeedtw',
				'testfeedfb' 		=> '/site/testfeedfb',
				'testjs' 			=> '/site/testjs',
				'test' 				=> '/site/test',
				'notified' 			=> '/site/notified',
				'thankyou' 			=> '/site/thankyou',
				'billing' 			=> '/site/billing',
				'paymentmethods' 	=> '/site/paymentmethods',
				'register' 			=> '/site/register',
				'activate' 			=> '/site/activate',
				'confirm' 			=> '/site/confirm',
				'login' 			=> '/site/login',
				'error' 			=> '/site/error',
				'login' 			=> '/site/login',
				'logout' 			=> '/site/logout',
				'testoffset'		=> '/site/testoffset',
				// '<controller:\w+>'=>'/site/<controller>',
				'<controller:\w+>/<id:\d+>'=>'<controller>/view',
				'<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
				'<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
				'<u:.*>'=>'/site/campaignfront',
			),
		),
		// uncomment the following to use a MySQL database
		'db'=>array(
			'connectionString' => 'mysql:host=localhost;dbname=beepond_db',
			'emulatePrepare' => true,
			'username' => 'ron',
			'password' => 'special1',
			'charset' => 'utf8',
		),
		'mongodb' => array(
			'class' => 'EMongoClient',
			// 'server' => 'mongodb://localhost:27017',
			'server' => 'mongodb://125.168.201.231:27017',
			'db' => 'super_test'
		),
		'errorHandler'=>array(
			// use 'site/error' action to display errors
			'errorAction'=>'site/error',
		),
		'log'=>array(
			'class'=>'CLogRouter',
			'routes'=>array(
				array(
					'class'=>'CFileLogRoute',
					'levels'=>'error, warning',
				),
				// uncomment the following to show log messages on web pages
				/*
				array(
					'class'=>'CWebLogRoute',
				),
				*/
			),
		),
	),

	// application-level parameters that can be accessed
	// using Yii::app()->params['paramName']
	'params'=>array(
		"adminEmail"=>"dothebest1@gmail.com", // diisi later
		"nameEmail"=>"Beepond",
		"noreplyEmail"=>"noreply@beepond.com",

		"elementsPerPage"=>10,

		"fbappid"=>"246290772075137",
		"fbappsecret"=>"c3949f6ad93c41101d395cb2f3527707",
		"fbpublicaccesstoken" => "CAACEdEose0cBAIbgZBVSZAH6NCEUUW0alklgJESw5UeFzZBbVBGDtR2FhrZCqRYry0KshBG1ewBPhZBlMhWOe0BFwfFbGdeuCyBNAUgbezg6TIUZCiehcQMhaeVWsDDq0G8s9bSkHLXc4DIvyrnqDwxVqbZAHbr1FI017UZAnBr5QXwtMB8wuNYqfbIjdfOC2cYD3VcpXWDKW7avZCbjZALuqV8MbC5oGy02IZD",
		"twconsumer_key"    => "cTMqudZQQdMTFueeUR9Z1Q",
		"twconsumer_secret" => "l28qK4myFVDHGTbapoMqfSEjMXQqTjiz1vXSsSUnE",
		"twuser_token"      => "1266766700-5OX9L2hVNnLNXAuWzjbYVmRXihMmB8IgUYxZWUa",
		"twuser_secret"     => "7gzgVcMta8opSCzkQlHf0RPPG7YqxyeKfSKeB8ItOE",
		"twfeedpercall"		=> 200,
		"googleapikey"		=> "AIzaSyC2qrP8czd1HH2alOFbIom1yhRLe86CLwI",
		"trconsumer_key"    => "zfY7EoN8nof2QZep0mbDHdkbdcYMCPFQzXlMUjfuRj8LGgJbNA",
		"trconsumer_secret" => "ziSUEuIv7f2DubhsdMnuVfXz0AgMekS95O34TdcHpEsf8voxfi",
		"igclient_id"       => "1f73a06be59f45a49909a32cab1c5900",
		"igclient_secret"   => "b9194ee8415e4ff58973ac717391e3ec",
		"igaccesstoken"		=> "29089265.1f73a06.b86d89c21ae14da3a8fb438c3f85d81c", // Refer to http://jelled.com/instagram/access-token to get accesstoken


		"campaignsource"=>array(
			"fb" => "facebook",
			"tw" => "twitter",
			"ig" => "instagram",
			// "tr" => "tumblr",
			// "yt" => "youtube",
			// "pt" => "pinterest",
		),
		"https"=>array(
			0=>"http://",
			1=>"https://"
		),
		"plantype"=>array(
			0=>"Free Trial — $0.00",
			1=>"Production — $149.00/month"
			// 2=>"Production 3 — $447.00/quarter",
			// 3=>"Production 6 — $849.30/biannual (5% OFF)",
			// 4=>"Production 12 — $1,609.20/year (10% OFF)"
		),
		"plancost"=>array(
			0=>0,
			1=>0.01,
		),
		"visibility"=>array(
			0=>"Private — Just me",
			1=>"Public, on Scheduled — Everyone"
		),
		"captiontextsize" => array(
			10=>"10px",
			11=>"11px",
			12=>"12px",
			13=>"13px",
			14=>"14px",
			15=>"15px",
			16=>"16px",
		),
		"blockpaddingsize" => array(
			0=>"0px",
			2=>"2px",
			4=>"4px",
			6=>"6px",
			8=>"8px",
			10=>"10px",
			12=>"12px",
			14=>"14px",
			16=>"16px",
			18=>"18px",
			20=>"20px",
		),
		'countries'	=> array(
			'0'=>"Select country",
			'US'=>'United States of America',
			'GB'=>'United Kingdom',
			'AU'=>'Australia',
			''=>"---------------------",
			'AF'=>'Afghanistan',
			'AX'=>'Aland Islands',
			'AL'=>'Albania',
			'DZ'=>'Algeria',
			'AS'=>'American Samoa',
			'AD'=>'Andorra',
			'AO'=>'Angola',
			'AI'=>'Anguilla',
			'AQ'=>'Antarctica',
			'AG'=>'Antigua and Barbuda',
			'AR'=>'Argentina',
			'AM'=>'Armenia',
			'AW'=>'Aruba',
			'AU'=>'Australia',
			'AT'=>'Austria',
			'AZ'=>'Azerbaijan',
			'BS'=>'Bahamas the',
			'BH'=>'Bahrain',
			'BD'=>'Bangladesh',
			'BB'=>'Barbados',
			'BY'=>'Belarus',
			'BE'=>'Belgium',
			'BZ'=>'Belize',
			'BJ'=>'Benin',
			'BM'=>'Bermuda',
			'BT'=>'Bhutan',
			'BO'=>'Bolivia',
			'BA'=>'Bosnia and Herzegovina',
			'BW'=>'Botswana',
			'BV'=>'Bouvet Island (Bouvetoya)',
			'BR'=>'Brazil',
			'IO'=>'British Indian Ocean Territory (Chagos Archipelago)',
			'VG'=>'British Virgin Islands',
			'BN'=>'Brunei Darussalam',
			'BG'=>'Bulgaria',
			'BF'=>'Burkina Faso',
			'BI'=>'Burundi',
			'KH'=>'Cambodia',
			'CM'=>'Cameroon',
			'CA'=>'Canada',
			'CV'=>'Cape Verde',
			'KY'=>'Cayman Islands',
			'CF'=>'Central African Republic',
			'TD'=>'Chad',
			'CL'=>'Chile',
			'CN'=>'China',
			'CX'=>'Christmas Island',
			'CC'=>'Cocos (Keeling) Islands',
			'CO'=>'Colombia',
			'KM'=>'Comoros the',
			'CD'=>'Congo',
			'CG'=>'Congo the',
			'CK'=>'Cook Islands',
			'CR'=>'Costa Rica',
			'CI'=>"Cote d'Ivoire",
			'HR'=>'Croatia',
			'CU'=>'Cuba',
			'CY'=>'Cyprus',
			'CZ'=>'Czech Republic',
			'DK'=>'Denmark',
			'DJ'=>'Djibouti',
			'DM'=>'Dominica',
			'DO'=>'Dominican Republic',
			'EC'=>'Ecuador',
			'EG'=>'Egypt',
			'SV'=>'El Salvador',
			'GQ'=>'Equatorial Guinea',
			'ER'=>'Eritrea',
			'EE'=>'Estonia',
			'ET'=>'Ethiopia',
			'FO'=>'Faroe Islands',
			'FK'=>'Falkland Islands (Malvinas)',
			'FJ'=>'Fiji the Fiji Islands',
			'FI'=>'Finland',
			'FR'=>'France, French Republic',
			'GF'=>'French Guiana',
			'PF'=>'French Polynesia',
			'TF'=>'French Southern Territories',
			'GA'=>'Gabon',
			'GM'=>'Gambia the',
			'GE'=>'Georgia',
			'DE'=>'Germany',
			'GH'=>'Ghana',
			'GI'=>'Gibraltar',
			'GR'=>'Greece',
			'GL'=>'Greenland',
			'GD'=>'Grenada',
			'GP'=>'Guadeloupe',
			'GU'=>'Guam',
			'GT'=>'Guatemala',
			'GG'=>'Guernsey',
			'GN'=>'Guinea',
			'GW'=>'Guinea-Bissau',
			'GY'=>'Guyana',
			'HT'=>'Haiti',
			'HM'=>'Heard Island and McDonald Islands',
			'VA'=>'Holy See (Vatican City State)',
			'HN'=>'Honduras',
			'HK'=>'Hong Kong',
			'HU'=>'Hungary',
			'IS'=>'Iceland',
			'IN'=>'India',
			'ID'=>'Indonesia',
			'IR'=>'Iran',
			'IQ'=>'Iraq',
			'IE'=>'Ireland',
			'IM'=>'Isle of Man',
			'IL'=>'Israel',
			'IT'=>'Italy',
			'CI'=>'Ivory Coast',
			'JM'=>'Jamaica',
			'JP'=>'Japan',
			'JE'=>'Jersey',
			'JO'=>'Jordan',
			'KZ'=>'Kazakhstan',
			'KE'=>'Kenya',
			'KI'=>'Kiribati',
			'KP'=>'Korea North',
			'KR'=>'Korea South',
			'KW'=>'Kuwait',
			'KG'=>'Kyrgyz Republic',
			'LA'=>'Lao',
			'LV'=>'Latvia',
			'LB'=>'Lebanon',
			'LS'=>'Lesotho',
			'LR'=>'Liberia',
			'LY'=>'Libyan Arab Jamahiriya',
			'LI'=>'Liechtenstein',
			'LT'=>'Lithuania',
			'LU'=>'Luxembourg',
			'MO'=>'Macao',
			'MK'=>'Macedonia',
			'MG'=>'Madagascar',
			'MW'=>'Malawi',
			'MY'=>'Malaysia',
			'MV'=>'Maldives',
			'ML'=>'Mali',
			'MT'=>'Malta',
			'MH'=>'Marshall Islands',
			'MQ'=>'Martinique',
			'MR'=>'Mauritania',
			'MU'=>'Mauritius',
			'YT'=>'Mayotte',
			'MX'=>'Mexico',
			'FM'=>'Micronesia',
			'MD'=>'Moldova',
			'MC'=>'Monaco',
			'MN'=>'Mongolia',
			'ME'=>'Montenegro',
			'MS'=>'Montserrat',
			'MA'=>'Morocco',
			'MZ'=>'Mozambique',
			'MM'=>'Myanmar',
			'NA'=>'Namibia',
			'NR'=>'Nauru',
			'NP'=>'Nepal',
			'AN'=>'Netherlands Antilles',
			'NL'=>'Netherlands the',
			'NC'=>'New Caledonia',
			'NZ'=>'New Zealand',
			'NI'=>'Nicaragua',
			'NE'=>'Niger',
			'NG'=>'Nigeria',
			'NU'=>'Niue',
			'NF'=>'Norfolk Island',
			'MP'=>'Northern Mariana Islands',
			'NO'=>'Norway',
			'OM'=>'Oman',
			'PK'=>'Pakistan',
			'PW'=>'Palau',
			'PS'=>'Palestinian Territory',
			'PA'=>'Panama',
			'PG'=>'Papua New Guinea',
			'PY'=>'Paraguay',
			'PE'=>'Peru',
			'PH'=>'Philippines',
			'PN'=>'Pitcairn Islands',
			'PL'=>'Poland',
			'PT'=>'Portugal, Portuguese Republic',
			'PR'=>'Puerto Rico',
			'QA'=>'Qatar',
			'RE'=>'Reunion',
			'RO'=>'Romania',
			'RU'=>'Russian Federation',
			'RW'=>'Rwanda',
			'BL'=>'Saint Barthelemy',
			'SH'=>'Saint Helena',
			'KN'=>'Saint Kitts and Nevis',
			'LC'=>'Saint Lucia',
			'MF'=>'Saint Martin',
			'PM'=>'Saint Pierre and Miquelon',
			'VC'=>'Saint Vincent and the Grenadines',
			'WS'=>'Samoa',
			'SM'=>'San Marino',
			'ST'=>'Sao Tome and Principe',
			'SA'=>'Saudi Arabia',
			'SN'=>'Senegal',
			'RS'=>'Serbia',
			'SC'=>'Seychelles',
			'SL'=>'Sierra Leone',
			'SG'=>'Singapore',
			'SK'=>'Slovakia (Slovak Republic)',
			'SI'=>'Slovenia',
			'SB'=>'Solomon Islands',
			'SO'=>'Somalia, Somali Republic',
			'ZA'=>'South Africa',
			'GS'=>'South Georgia and the South Sandwich Islands',
			'ES'=>'Spain',
			'LK'=>'Sri Lanka',
			'SD'=>'Sudan',
			'SR'=>'Suriname',
			'SJ'=>'Svalbard & Jan Mayen Islands',
			'SZ'=>'Swaziland',
			'SE'=>'Sweden',
			'CH'=>'Switzerland, Swiss Confederation',
			'SY'=>'Syrian Arab Republic',
			'TW'=>'Taiwan',
			'TJ'=>'Tajikistan',
			'TZ'=>'Tanzania',
			'TH'=>'Thailand',
			'TL'=>'Timor-Leste',
			'TG'=>'Togo',
			'TK'=>'Tokelau',
			'TO'=>'Tonga',
			'TT'=>'Trinidad and Tobago',
			'TN'=>'Tunisia',
			'TR'=>'Turkey',
			'TM'=>'Turkmenistan',
			'TC'=>'Turks and Caicos Islands',
			'TV'=>'Tuvalu',
			'UG'=>'Uganda',
			'UA'=>'Ukraine',
			'AE'=>'United Arab Emirates',
			'GB'=>'United Kingdom',
			'US'=>'United States of America',
			'UM'=>'United States Minor Outlying Islands',
			'VI'=>'United States Virgin Islands',
			'UY'=>'Uruguay, Eastern Republic of',
			'UZ'=>'Uzbekistan',
			'VU'=>'Vanuatu',
			'VE'=>'Venezuela',
			'VN'=>'Vietnam',
			'WF'=>'Wallis and Futuna',
			'EH'=>'Western Sahara',
			'YE'=>'Yemen',
			'ZM'=>'Zambia',
			'ZW'=>'Zimbabwe'
		),
		'languages'=>array(
			'en'=>'English',
			'zh'=>'Chinese',
			''=>'-----------',
			'aa' => 'Afar',
			'ab' => 'Abkhaz',
			'ae' => 'Avestan',
			'af' => 'Afrikaans',
			'ak' => 'Akan',
			'am' => 'Amharic',
			'an' => 'Aragonese',
			'ar' => 'Arabic',
			'as' => 'Assamese',
			'av' => 'Avaric',
			'ay' => 'Aymara',
			'az' => 'Azerbaijani',
			'ba' => 'Bashkir',
			'be' => 'Belarusian',
			'bg' => 'Bulgarian',
			'bh' => 'Bihari',
			'bi' => 'Bislama',
			'bm' => 'Bambara',
			'bn' => 'Bengali',
			'bo' => 'Tibetan Standard, Tibetan, Central',
			'br' => 'Breton',
			'bs' => 'Bosnian',
			'ca' => 'Catalan; Valencian',
			'ce' => 'Chechen',
			'ch' => 'Chamorro',
			'co' => 'Corsican',
			'cr' => 'Cree',
			'cs' => 'Czech',
			'cu' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
			'cv' => 'Chuvash',
			'cy' => 'Welsh',
			'da' => 'Danish',
			'de' => 'German',
			'dv' => 'Divehi; Dhivehi; Maldivian;',
			'dz' => 'Dzongkha',
			'ee' => 'Ewe',
			'el' => 'Greek, Modern',
			'en' => 'English',
			'eo' => 'Esperanto',
			'es' => 'Spanish; Castilian',
			'et' => 'Estonian',
			'eu' => 'Basque',
			'fa' => 'Persian',
			'ff' => 'Fula; Fulah; Pulaar; Pular',
			'fi' => 'Finnish',
			'fj' => 'Fijian',
			'fo' => 'Faroese',
			'fr' => 'French',
			'fy' => 'Western Frisian',
			'ga' => 'Irish',
			'gd' => 'Scottish Gaelic; Gaelic',
			'gl' => 'Galician',
			'gn' => 'GuaranÃ­',
			'gu' => 'Gujarati',
			'gv' => 'Manx',
			'ha' => 'Hausa',
			'he' => 'Hebrew (modern)',
			'hi' => 'Hindi',
			'ho' => 'Hiri Motu',
			'hr' => 'Croatian',
			'ht' => 'Haitian; Haitian Creole',
			'hu' => 'Hungarian',
			'hy' => 'Armenian',
			'hz' => 'Herero',
			'ia' => 'Interlingua',
			'id' => 'Indonesian',
			'ie' => 'Interlingue',
			'ig' => 'Igbo',
			'ii' => 'Nuosu',
			'ik' => 'Inupiaq',
			'io' => 'Ido',
			'is' => 'Icelandic',
			'it' => 'Italian',
			'iu' => 'Inuktitut',
			'ja' => 'Japanese (ja)',
			'jv' => 'Javanese (jv)',
			'ka' => 'Georgian',
			'kg' => 'Kongo',
			'ki' => 'Kikuyu, Gikuyu',
			'kj' => 'Kwanyama, Kuanyama',
			'kk' => 'Kazakh',
			'kl' => 'Kalaallisut, Greenlandic',
			'km' => 'Khmer',
			'kn' => 'Kannada',
			'ko' => 'Korean',
			'kr' => 'Kanuri',
			'ks' => 'Kashmiri',
			'ku' => 'Kurdish',
			'kv' => 'Komi',
			'kw' => 'Cornish',
			'ky' => 'Kirghiz, Kyrgyz',
			'la' => 'Latin',
			'lb' => 'Luxembourgish, Letzeburgesch',
			'lg' => 'Luganda',
			'li' => 'Limburgish, Limburgan, Limburger',
			'ln' => 'Lingala',
			'lo' => 'Lao',
			'lt' => 'Lithuanian',
			'lu' => 'Luba-Katanga',
			'lv' => 'Latvian',
			'mg' => 'Malagasy',
			'mh' => 'Marshallese',
			'mi' => 'Maori',
			'mk' => 'Macedonian',
			'ml' => 'Malayalam',
			'mn' => 'Mongolian',
			'mr' => 'Marathi (Mara?hi)',
			'ms' => 'Malay',
			'mt' => 'Maltese',
			'my' => 'Burmese',
			'na' => 'Nauru',
			'nb' => 'Norwegian BokmÃ¥l',
			'nd' => 'North Ndebele',
			'ne' => 'Nepali',
			'ng' => 'Ndonga',
			'nl' => 'Dutch',
			'nn' => 'Norwegian Nynorsk',
			'no' => 'Norwegian',
			'nr' => 'South Ndebele',
			'nv' => 'Navajo, Navaho',
			'ny' => 'Chichewa; Chewa; Nyanja',
			'oc' => 'Occitan',
			'oj' => 'Ojibwe, Ojibwa',
			'om' => 'Oromo',
			'or' => 'Oriya',
			'os' => 'Ossetian, Ossetic',
			'pa' => 'Panjabi, Punjabi',
			'pi' => 'Pali',
			'pl' => 'Polish',
			'ps' => 'Pashto, Pushto',
			'pt' => 'Portuguese',
			'qu' => 'Quechua',
			'rm' => 'Romansh',
			'rn' => 'Kirundi',
			'ro' => 'Romanian, Moldavian, Moldovan',
			'ru' => 'Russian',
			'rw' => 'Kinyarwanda',
			'sa' => 'Sanskrit (Sa?sk?ta)',
			'sc' => 'Sardinian',
			'sd' => 'Sindhi',
			'se' => 'Northern Sami',
			'sg' => 'Sango',
			'si' => 'Sinhala, Sinhalese',
			'sk' => 'Slovak',
			'sl' => 'Slovene',
			'sm' => 'Samoan',
			'sn' => 'Shona',
			'so' => 'Somali',
			'sq' => 'Albanian',
			'sr' => 'Serbian',
			'ss' => 'Swati',
			'st' => 'Southern Sotho',
			'su' => 'Sundanese',
			'sv' => 'Swedish',
			'sw' => 'Swahili',
			'ta' => 'Tamil',
			'te' => 'Telugu',
			'tg' => 'Tajik',
			'th' => 'Thai',
			'ti' => 'Tigrinya',
			'tk' => 'Turkmen',
			'tl' => 'Tagalog',
			'tn' => 'Tswana',
			'to' => 'Tonga (Tonga Islands)',
			'tr' => 'Turkish',
			'ts' => 'Tsonga',
			'tt' => 'Tatar',
			'tw' => 'Twi',
			'ty' => 'Tahitian',
			'ug' => 'Uighur, Uyghur',
			'uk' => 'Ukrainian',
			'ur' => 'Urdu',
			'uz' => 'Uzbek',
			've' => 'Venda',
			'vi' => 'Vietnamese',
			'vo' => 'VolapÃ¼k',
			'wa' => 'Walloon',
			'wo' => 'Wolof',
			'xh' => 'Xhosa',
			'yi' => 'Yiddish',
			'yo' => 'Yoruba',
			'za' => 'Zhuang, Chuang',
			'zh' => 'Chinese',
			'zu' => 'Zulu',
		),
		'timezone'=>array(
			'-12'  => '(GMT-12:00) Eniwetok, Kwajalein',
			'-11'  => '(GMT-11:00) Midway Island, Samoa',
			'-10'  => '(GMT-10:00) Hawaii',
			'-9'   => '(GMT-9:00) Alaska',
			'-8'   => '(GMT-8:00) Pacific Time (US & Canada)',
			'-7'   => '(GMT-7:00) Mountain Time (US & Canada)',
			'-6'   => '(GMT-6:00) Central Time (US & Canada), Mexico City',
			'-5'   => '(GMT-5:00) Eastern Time (US & Canada), Bogota, Lima, Quito',
			'-4'   => '(GMT-4:00) Atlantic Time (Canada), Caracas, La Paz',
			'-3.5' => '(GMT-3:30) Newfoundland',
			'-3'   => '(GMT-3:00) Brasilia, Buenos Aires, Georgetown',
			'-2'   => '(GMT-2:00) Mid-Atlantic',
			'-1'   => '(GMT-1:00) Azores, Cape Verde Islands',
			'0'    => '(GMT) Greenwich Mean Time, London, Dublin, Lisbon, Casablanca, Monrovia',
			'+1'   => '(GMT+1:00) Amsterdam, Berlin, Rome, Copenhagen, Brussels, Madrid, Paris',
			'+2'   => '(GMT+2:00) Athens, Istanbul, Minsk, Helsinki, Jerusalem, South Africa',
			'+3'   => '(GMT+3:00) Baghdad, Kuwait, Riyadh, Moscow, St. Petersburg',
			'+3.5' => '(GMT+3:30) Tehran',
			'+4'   => '(GMT+4:00) Abu Dhabi, Muscat, Baku, Tbilisi',
			'+4.5' => '(GMT+4:30) Kabul',
			'+5'   => '(GMT+5:00) Ekaterinburg, Islamabad, Karachi, Tashkent',
			'+5.5' => '(GMT+5:30) Bombay, Calcutta, Madras, New Delhi',
			'+6'   => '(GMT+6:00) Almaty, Dhaka, Colombo',
			'+7'   => '(GMT+7:00) Bangkok, Hanoi, Jakarta',
			'+8'   => '(GMT+8:00) Beijing, Perth, Singapore, Hong Kong, Urumqi, Taipei',
			'+9'   => '(GMT+9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk',
			'+9.5' => '(GMT+9:30) Adelaide, Darwin',
			'+10'  => '(GMT+10:00) Brisbane, Canberra, Melbourne, Sydney, Guam,Vlasdiostok',
			'+11'  => '(GMT+11:00) Magadan, Solomon Islands, New Caledonia',
			'+12'  => '(GMT+12:00) Auckland, Wellington, Fiji, Kamchatka, Marshall Island',
		),
	),
);